//
//  ListGradeViewController.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListGradeViewControllerInput {
    func displaySomething(viewModel: ListGradeViewModel)
}

protocol ListGradeViewControllerOutput {
    func doSomething(request: ListGradeRequest)
}

class ListGradeViewController: UITableViewController, ListGradeViewControllerInput {
    var output: ListGradeViewControllerOutput!
    var router: ListGradeRouter!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        ListGradeConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work
        
        let request = ListGradeRequest()
        output.doSomething(request)
    }
    
    // MARK: Display logic
    
    func displaySomething(viewModel: ListGradeViewModel) {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}
