//
//  ListGradeInteractor.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListGradeInteractorInput {
    func fetchGrades(request: ListGradeRequest)
}

protocol ListGradeInteractorOutput {
    func presentFetchedGrades(response: ListGradeResponse)
}

class ListGradeInteractor: ListGradeInteractorInput {
    var output: ListGradeInteractorOutput!
    var worker: ListGradeWorker!
    
    // MARK: Business logic
    
    func fetchGrades(request: ListGradeRequest) {
        // NOTE: Create some Worker to do the work
        
        worker = ListGradeWorker()
        worker.fetchGrades { (grades, error) in
            let response = ListGradeResponse(grades: grades, error: error)
            self.output.presentFetchedGrades(response)
        }
        
    }
}
