//
//  ListGradeViewController.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListGradeTableViewControllerInput {
    func displayFetchedGrades(_ viewModel: ListGradeViewModel.Success)
    func displayFetchedGradesError(_ viewModel: ListGradeViewModel.Error)
}

protocol ListGradeTableViewControllerOutput {
    func fetchGrades(_ request: ListGradeRequest)
}

class ListGradeTableViewController: UITableViewController, ListGradeTableViewControllerInput {
    var output: ListGradeTableViewControllerOutput!
    var router: ListGradeRouter!
    var grades:[Grade] = []
    
    let defaultCellIdentifier = "defaultCell"
    let emptyCellIdentifier = "emptyCell"
    let loadingCellIdentifier = "loadingCell"
    var firstLoadingFlag = true
    
    @IBOutlet weak var reloadButtonItem: UIBarButtonItem!
    
    // Interface Animation Parameters
    var selectedCellIndexPath:IndexPath?
    let selectedCellHeight:CGFloat = 293
    let unselectedCellHeight:CGFloat = 58
    let school31CellHeight:CGFloat = 80
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        ListGradeConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomethingOnLoad()
        configInterfaceAnimations()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        if self.selectedCellIndexPath != nil {
            self.tableView.deselectRow(at: self.selectedCellIndexPath!, animated: false)
            self.selectedCellIndexPath = nil
        }
        self.tableView.beginUpdates()
        self.tableView.endUpdates()
    }
    
    // MARK: Interface Animation
    
    override func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 0.0001
    }
    
    override func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        return 0.0001
    }
    
    func configInterfaceAnimations() {
        self.refreshControl?.addTarget(self, action: #selector(ListGradeTableViewController.handleRefresh(_:)), for: .valueChanged)
    }
    
    fileprivate func startReloadAnimation() {
        reloadButtonItem.isEnabled = false
        self.navigationItem.title = "Carregando Notas"
    }
    
    fileprivate func stopReloadAnimation() {
        reloadButtonItem.isEnabled = true
        refreshControl?.endRefreshing()
        self.navigationItem.title = "Notas"
    }
    
    func handleRefresh(_ refreshControl: UIRefreshControl) {
        startReloadAnimation()
        let delayInSeconds = 1.0;
        let popTime = DispatchTime.now() + Double(Int64(delayInSeconds * Double(NSEC_PER_SEC))) / Double(NSEC_PER_SEC);
        DispatchQueue.main.asyncAfter(deadline: popTime) { [unowned self] () -> Void in
            self.fetchGrades()
        }
    }
    
    // MARK: Event handling
    
    fileprivate func fetchGrades() {
        startReloadAnimation()
        let request = ListGradeRequest()
        output.fetchGrades(request)
    }
    
    @IBAction func reloadData(_ sender: AnyObject) {
        self.fetchGrades()
    }
    
    fileprivate func doSomethingOnLoad() -> Void {
        self.fetchGrades()
    }
    
    // MARK: Display logic
    
    func displayFetchedGrades(_ viewModel: ListGradeViewModel.Success) {
        self.stopReloadAnimation()
        
        self.grades = viewModel.grades
        self.firstLoadingFlag = false
        DispatchQueue.main.async { 
            self.tableView.reloadData()
        }
    }
    
    func displayFetchedGradesError(_ viewModel: ListGradeViewModel.Error) {
        self.stopReloadAnimation()
        
        let alert = UIAlertController(title: viewModel.errorTitle, message: viewModel.errorMessage, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }
}

extension ListGradeTableViewController {
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if indexPath != self.selectedCellIndexPath {
            self.selectedCellIndexPath = indexPath
        } else {
            if let _ = self.selectedCellIndexPath {
                self.tableView.deselectRow(at: self.selectedCellIndexPath!, animated: true)
            }
            self.selectedCellIndexPath = nil
        }
        
        self.tableView.beginUpdates()
        self.tableView.endUpdates()
    }
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        
        let number = self.grades.count
        
        if number == 0 {
            return 1
        }
        return number
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        if self.grades.count == 0 {
            if self.firstLoadingFlag {
                let cell = tableView.dequeueReusableCell(withIdentifier: self.loadingCellIdentifier) ?? UITableViewCell()
                return cell
            } else {
                let cell = tableView.dequeueReusableCell(withIdentifier: self.emptyCellIdentifier) ?? UITableViewCell()
                return cell
            }
        }
        
        if grades[(indexPath as NSIndexPath).row].schoolCode.range(of: "31") != nil {
            let cell = tableView.dequeueReusableCell(withIdentifier: "grade31SchoolCell")
            cell?.textLabel?.text = grades[(indexPath as NSIndexPath).row].className
            cell?.detailTextLabel?.text = "Em desenvolvimento - FAU"
            return cell!
        }
        
        let cell = tableView.dequeueReusableCell(withIdentifier: self.defaultCellIdentifier) as! ListGradeTableViewCell
        cell.config(grades[(indexPath as NSIndexPath).row])
        return cell
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        
        if grades.count == 0 {
            return 100.0
        }
        
        if grades[(indexPath as NSIndexPath).row].schoolCode.range(of: "31") != nil {
            return self.school31CellHeight
        }
        
        if self.selectedCellIndexPath == indexPath {
            return self.selectedCellHeight
        }
        return self.unselectedCellHeight
    }
    
    override func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        
        // Remove seperator inset
        if cell.responds(to: #selector(setter: UITableViewCell.separatorInset)) {
            cell.separatorInset = UIEdgeInsets.zero
        }
        
        // Prevent the cell from inheriting the Table View's margin settings
        if cell.responds(to: #selector(setter: UIView.preservesSuperviewLayoutMargins)) {
            cell.preservesSuperviewLayoutMargins = false
        }
        
        // Explictly set your cell's layout margins
        if cell.responds(to: #selector(setter: UIView.layoutMargins)) {
            cell.layoutMargins = UIEdgeInsets.zero
        }
    }
}
