//
//  ListGradePresenter.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListGradePresenterInput {
    func presentFetchedGrades(response: ListGradeResponse)
}

protocol ListGradePresenterOutput: class {
    func displayFetchedGrades(viewModel: ListGradeViewModel)
}

class ListGradePresenter: ListGradePresenterInput {
    weak var output: ListGradePresenterOutput!
    
    // MARK: Presentation logic
    
    func presentFetchedGrades(response: ListGradeResponse) {
        
        var error:(title:String,message:String)?
        
        if response.error != nil {
            error = ErrorParser.parse(response.error!)
        }
        
        let viewModel = ListGradeViewModel(grades: response.grades, errorMessage: error?.message, errorTitle: error?.title)
        output.displayFetchedGrades(viewModel)
    }
}
