//
//  ListGradeInteractor.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListGradeInteractorInput {
    func doSomething(request: ListGradeRequest)
}

protocol ListGradeInteractorOutput {
    func presentSomething(response: ListGradeResponse)
}

class ListGradeInteractor: ListGradeInteractorInput {
    var output: ListGradeInteractorOutput!
    var worker: ListGradeWorker!
    
    // MARK: Business logic
    
    func doSomething(request: ListGradeRequest) {
        // NOTE: Create some Worker to do the work
        
        worker = ListGradeWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = ListGradeResponse()
        output.presentSomething(response)
    }
}
