//
//  ListGradePresenter.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListGradePresenterInput {
    func presentSomething(response: ListGradeResponse)
}

protocol ListGradePresenterOutput: class {
    func displaySomething(viewModel: ListGradeViewModel)
}

class ListGradePresenter: ListGradePresenterInput {
    weak var output: ListGradePresenterOutput!
    
    // MARK: Presentation logic
    
    func presentSomething(response: ListGradeResponse) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        
        let viewModel = ListGradeViewModel()
        output.displaySomething(viewModel)
    }
}
