//
//  LoginPresenter.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginPresenterInput {
    func presentLoginError(_ response: LoginResponse)
    func presentLoginAccepted()
}

protocol LoginPresenterOutput: class {
    func displayLoginFailure(_ viewModel: LoginViewModel)
    func loginAccepted()
}

class LoginPresenter: LoginPresenterInput {
    weak var output: LoginPresenterOutput!
    
    // MARK: Presentation logic
    
    func presentLoginError(_ response: LoginResponse) {
        
        let errorTitle = NSLocalizedString("login_defaultErrorTitle", comment: "Login Error Title")
        let errorMessage = NSLocalizedString("login_defaultErrorMessage", comment: "Default login error message")
        
        guard response.error != nil else {
            let viewModel = LoginViewModel(errorMessage: errorMessage, errorTitle: errorTitle)
            output.displayLoginFailure(viewModel)
            return
        }
        
        let error = ErrorParser.parse(response.error!)
        let viewModel = LoginViewModel(errorMessage: error.message, errorTitle: error.title)
        output.displayLoginFailure(viewModel)
    }
    
    func presentLoginAccepted() {
        self.output.loginAccepted()
    }
}
