//
//  LoginRouter.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginRouterInput {
  func navigateToMainView()
}

class LoginRouter: LoginRouterInput {
  weak var viewController: LoginViewController!
  
  // MARK: Navigation
  
  func navigateToMainView() {
    if let _ = UserDefaults.standard.object(forKey: "statement") as? String {
        viewController.performSegue(withIdentifier: "login", sender: nil)
    }
    viewController.performSegue(withIdentifier: "firstLogin", sender: nil)
  }
  
  // MARK: Communication
  
  func passDataToNextScene(_ segue: UIStoryboardSegue) {
    // NOTE: Teach the router which scenes it can communicate with
    
    // if segue.identifier == "mainView" {
    //   passDataToSomewhereScene(segue)
    // }
  }
  
  func passDataToSomewhereScene(_ segue: UIStoryboardSegue) {
    // NOTE: Teach the router how to pass data to the next scene

    // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
    // someWhereViewController.output.name = viewController.output.name
  }
}
