//
//  LoginViewController.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Fabric
import Crashlytics

// Metodos que poderao ser invocados pelo Presenter
protocol LoginViewControllerInput
{
    func displayLoginFailure(_ viewModel: LoginViewModel)
    func loginAccepted()
}

// Metodos que podem ser invocados no Interector
protocol LoginViewControllerOutput
{
    func validateLogin(_ request: LoginRequest)
}

class LoginViewController: UIViewController, AKPickerViewDataSource, AKPickerViewDelegate, UITextFieldDelegate, LoginViewControllerInput
{
    @IBOutlet weak var tiaTextField: UITextField!
    @IBOutlet weak var passTextField: UITextField!
    @IBOutlet weak var loginButton: UIButton!
    @IBOutlet weak var campusPickerView: AKPickerView!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet weak var whaitingView: UIVisualEffectView!
    @IBOutlet weak var bottomConstraint: NSLayoutConstraint!
    
    var campus:Array<String> {
        return [" Rio de Janeiro "," São Paulo "," Brasília "," UATU "]
    }
    var campusCode:Array<String> {
        return ["006","001","003","011"]
    }
    
    // MARK: VIPER properties
    var output: LoginViewControllerOutput!
    var router: LoginRouter!
    
    
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        LoginConfigurator.sharedInstance.configure(self)
    }
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.configView()
    }
    
    fileprivate func configView() {
        let paddingViewTia = UIView(frame: CGRect(x: 0, y: 0, width: 15, height: 50))
        let paddingViewPass = UIView(frame: CGRect(x: 0, y: 0, width: 15, height: 50))
        
        let tiaPlaceholder = NSMutableAttributedString(string: NSLocalizedString("tia", comment: "Student Identification")) // Localized text here!
        
        self.tiaTextField.layer.cornerRadius = 7
        self.tiaTextField.leftView = paddingViewTia
        self.tiaTextField.leftViewMode = .always
        self.tiaTextField.rightView = paddingViewTia
        self.tiaTextField.rightViewMode = .always
        self.tiaTextField.attributedPlaceholder = tiaPlaceholder
        
        let passPlaceholder = NSMutableAttributedString(string: NSLocalizedString("password", comment: "Password Placeholder")) // Localized text here!
        
        self.passTextField.layer.cornerRadius = 7
        self.passTextField.leftView = paddingViewPass
        self.passTextField.leftViewMode = .always
        self.passTextField.rightView = paddingViewPass
        self.passTextField.rightViewMode = .always
        self.passTextField.attributedPlaceholder = passPlaceholder
        
        self.loginButton.layer.cornerRadius = 7
        
        self.campusPickerView.delegate = self
        self.campusPickerView.dataSource = self
        self.campusPickerView.layer.cornerRadius = 7
        self.campusPickerView.selectItem(1, animated: false)
        self.campusPickerView.textColor = UIColor(red: 1, green: 1, blue: 1, alpha: 0.7)
        self.campusPickerView.highlightedTextColor = UIColor.white
        
        // este codigo existe para que na storyboard a view e o activityIndicator possam ficar de fundo sem atrapalhar o trabalho do desgin
        self.view.bringSubview(toFront: self.whaitingView)
        self.view.bringSubview(toFront: self.activityIndicator)
        self.activityIndicator.isHidden = true
        self.whaitingView.isHidden = true
        
        // Observer keyboard events
        NotificationCenter.default.addObserver(self, selector: #selector(LoginViewController.keyboardWasShow(_:)), name:NSNotification.Name.UIKeyboardWillShow, object: nil);
        NotificationCenter.default.addObserver(self, selector: #selector(LoginViewController.keyboardWasHide(_:)), name:NSNotification.Name.UIKeyboardWillHide, object: nil);
    }
    
    override var prefersStatusBarHidden : Bool {
        return true
    }
    
    // Necessario para evitar problema com notificacoes enviadas para VC que nao existe mais
    deinit {
        NotificationCenter.default.removeObserver(self);
    }
    
    // Necessario para remover teclado da tela caso o usario toque fora dele
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        self.view.endEditing(true)
    }
    
    // MARK: Event handling
    
    @IBAction func login(_ sender: AnyObject) {
        // prepare interface
        self.whaitingView.isHidden = false
        self.activityIndicator.startAnimating()
        
        // get interface data
        let tia = tiaTextField.text!
        let password = passTextField.text!
        let campus = self.campusCode[self.campusPickerView.selectedItem]
        
        // invoke interector
        let request = LoginRequest(tia: tia, password: password, campus: campus)
        self.output.validateLogin(request)
    }
    
    
    
    // MARK: Display logic
    
    func displayLoginFailure(_ viewModel: LoginViewModel) {
        let alert = UIAlertController(title: viewModel.errorTitle, message: viewModel.errorMessage, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
        self.present(alert, animated: true) { 
            self.activityIndicator?.stopAnimating()
            self.whaitingView.isHidden = true
        }
        
        // FABRIC - Login error
        // TODO: melhorar o log no fabric
        Answers.logLogin(withMethod: "Digits", success: false, customAttributes: ["metodo":"login no servidor"])
    }
    
    func loginAccepted() {
        self.activityIndicator?.stopAnimating()
        self.router.navigateToMainView()
        
        // FABRIC - Login accpeted
        // TODO: conferir no fabric
        Answers.logLogin(withMethod: "Digits", success: false, customAttributes: ["metodo":"login no servidor"])
    }
    
    
    // MARK: Util Methods
    
    func keyboardWasShow(_ notification: Notification) {
        var info = (notification as NSNotification).userInfo!
        let keyboardFrame: CGRect = (info[UIKeyboardFrameEndUserInfoKey] as! NSValue).cgRectValue
        
        UIView.animate(withDuration: 0.5, animations: { () -> Void in
            self.bottomConstraint.constant = keyboardFrame.size.height + 20
            self.view.layoutIfNeeded()
        })
    }
    
    func keyboardWasHide(_ notification: Notification) {
        UIView.animate(withDuration: 0.5, animations: { () -> Void in
            self.bottomConstraint.constant = 102
            self.view.layoutIfNeeded()
        })
    }
    
    
    // MARK: - Memory Management
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - AKPickerView
    func numberOfItemsInPickerView(_ pickerView: AKPickerView) -> Int {
        return self.campus.count
    }
    
    func pickerView(_ pickerView: AKPickerView, titleForItem item: Int) -> String {
        return self.campus[item]
    }
    
    // MARK: - TextFieldDelegate
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        
        if textField == passTextField {
            self.login(self.loginButton)
        }
        
        let tag = textField.tag + 1
        if let superview = textField.superview {
            let nextTextField = superview.viewWithTag(tag)
            if nextTextField != nil {
                nextTextField?.becomeFirstResponder()
                return false
            }
        }
        textField.resignFirstResponder()
        return false
    }
    
    // MARK: Rotation Support
    
    override var supportedInterfaceOrientations : UIInterfaceOrientationMask {
        return UIInterfaceOrientationMask.portrait
    }
    
    override var shouldAutorotate : Bool {
        return false
    }
}
