//
//  LoginModels.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct LoginRequest
{
    var tia:String
    var password:String
    var campus:String
}

struct LoginResponse
{
    var error:ErrorCode?
}

struct LoginViewModel
{
    var errorMessage:String?
    var errorTitle:String?
}
