<?php

if ($_SERVER['REQUEST_METHOD'] == 'GET') {
  echo "Cannot GET";
  return;
}
header('Content-Type: application/json');
?>
{
  "resposta": [
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04803",
      "nome": "CIRCUITOS ELETRICOS I",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "07:30",
      "dia": "2",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04803",
      "nome": "CIRCUITOS ELETRICOS I",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "08:15",
      "dia": "2",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX01484",
      "nome": "CONVERSAO DE ENERGIA",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "09:05",
      "dia": "2",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX01484",
      "nome": "CONVERSAO DE ENERGIA",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "09:50",
      "dia": "2",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00926",
      "nome": "ELETRONICA APLICADA I",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "10:40",
      "dia": "2",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00926",
      "nome": "ELETRONICA APLICADA I",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "11:25",
      "dia": "2",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX01484",
      "nome": "CONVERSAO DE ENERGIA",
      "turma": "05E12",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "07:30",
      "dia": "3",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX01484",
      "nome": "CONVERSAO DE ENERGIA",
      "turma": "05E12",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "08:15",
      "dia": "3",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00926",
      "nome": "ELETRONICA APLICADA I",
      "turma": "05E11",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "09:05",
      "dia": "3",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00926",
      "nome": "ELETRONICA APLICADA I",
      "turma": "05E11",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "09:50",
      "dia": "3",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04803",
      "nome": "CIRCUITOS ELETRICOS I",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "07:30",
      "dia": "4",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04803",
      "nome": "CIRCUITOS ELETRICOS I",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "08:15",
      "dia": "4",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04955",
      "nome": "CIRCUITOS DIGITAIS I",
      "turma": "04E",
      "escola": "EE",
      "local": "0511301",
      "predio": "05",
      "sala": "301",
      "hora": "09:05",
      "dia": "4",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04955",
      "nome": "CIRCUITOS DIGITAIS I",
      "turma": "04E",
      "escola": "EE",
      "local": "0511301",
      "predio": "05",
      "sala": "301",
      "hora": "09:50",
      "dia": "4",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04803",
      "nome": "CIRCUITOS ELETRICOS I",
      "turma": "05E11",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "10:40",
      "dia": "4",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04803",
      "nome": "CIRCUITOS ELETRICOS I",
      "turma": "05E11",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "11:25",
      "dia": "4",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX01484",
      "nome": "CONVERSAO DE ENERGIA",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "07:30",
      "dia": "5",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX01484",
      "nome": "CONVERSAO DE ENERGIA",
      "turma": "05E",
      "escola": "EE",
      "local": "0611203",
      "predio": "06",
      "sala": "203",
      "hora": "08:15",
      "dia": "5",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00895",
      "nome": "CIRCUITOS DIGITAIS II",
      "turma": "05E11",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "10:40",
      "dia": "5",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00895",
      "nome": "CIRCUITOS DIGITAIS II",
      "turma": "05E11",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "11:25",
      "dia": "5",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04955",
      "nome": "CIRCUITOS DIGITAIS I",
      "turma": "04E12",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "07:30",
      "dia": "6",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEC04955",
      "nome": "CIRCUITOS DIGITAIS I",
      "turma": "04E12",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "08:15",
      "dia": "6",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00895",
      "nome": "CIRCUITOS DIGITAIS II",
      "turma": "05E",
      "escola": "EE",
      "local": "0511302",
      "predio": "05",
      "sala": "302",
      "hora": "09:05",
      "dia": "6",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00895",
      "nome": "CIRCUITOS DIGITAIS II",
      "turma": "05E",
      "escola": "EE",
      "local": "0511302",
      "predio": "05",
      "sala": "302",
      "hora": "09:50",
      "dia": "6",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00357",
      "nome": "APLICACOES COMPUT ENG ELETRICA",
      "turma": "04E12",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "10:40",
      "dia": "6",
      "update": "20160413"
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "codigo": "ENEX00357",
      "nome": "APLICACOES COMPUT ENG ELETRICA",
      "turma": "04E12",
      "escola": "EE",
      "local": "0611LES",
      "predio": "06",
      "sala": "LES",
      "hora": "11:25",
      "dia": "6",
      "update": "20160413"
    }
  ]
}
