{
  "resposta": [
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "Codigo": "ENEX00357",
      "Disciplina": "APLICACOES COMPUT ENG ELETRICA",
      "a": "8.5",
      "b": "",
      "c": "",
      "d": "",
      "e": "",
      "f": "",
      "g": "",
      "h": "",
      "i": "",
      "j": "",
      "n1": "8.5",
      "n2": "0.0",
      "mi": "2.5",
      "mfd": "1.2",
      "qual_sub": "",
      "pf": "",
      "data_a": "",
      "data_b": "",
      "data_c": "",
      "data_d": "",
      "data_e": "",
      "data_f": "",
      "data_g": "",
      "data_h": "",
      "data_i": "",
      "data_j": "",
      "falta": "00.00",
      "formula": "NI1  = (A*3)/3 NI2  = (F*2 + G*5)/7 MI = (NI1*3 + NI2*7) / 10 + PARTIC MF = (MI + PF) / 2",
      "Escola": ""
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "Codigo": "ENEC04955",
      "Disciplina": "CIRCUITOS DIGITAIS I",
      "a": "",
      "b": "",
      "c": "",
      "d": "",
      "e": "",
      "f": "",
      "g": "",
      "h": "",
      "i": "",
      "j": "",
      "n1": "",
      "n2": "",
      "mi": "",
      "mfd": "",
      "qual_sub": "",
      "pf": "",
      "data_a": "",
      "data_b": "",
      "data_c": "",
      "data_d": "",
      "data_e": "",
      "data_f": "",
      "data_g": "",
      "data_h": "",
      "data_i": "",
      "data_j": "",
      "falta": "02.60",
      "formula": "NÃO INFORMADA",
      "Escola": ""
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "Codigo": "ENEX00895",
      "Disciplina": "CIRCUITOS DIGITAIS II",
      "a": "",
      "b": "",
      "c": "",
      "d": "",
      "e": "",
      "f": "",
      "g": "",
      "h": "",
      "i": "",
      "j": "",
      "n1": "0.0",
      "n2": "0.0",
      "mi": "99.9",
      "mfd": "99.9",
      "qual_sub": "",
      "pf": "",
      "data_a": "",
      "data_b": "",
      "data_c": "",
      "data_d": "",
      "data_e": "",
      "data_f": "",
      "data_g": "",
      "data_h": "",
      "data_i": "",
      "data_j": "",
      "falta": "00.00",
      "formula": "NI1  = (A*10)/10 NI2  = (F*2 + G*8)/10 MI = (NI1*3 + NI2*7) / 10 + PARTIC MF = (MI + PF) / 2",
      "Escola": ""
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "Codigo": "ENEC04803",
      "Disciplina": "CIRCUITOS ELETRICOS I",
      "a": "10.0",
      "b": "10.0",
      "c": "8.0",
      "d": "",
      "e": "",
      "f": "",
      "g": "",
      "h": "",
      "i": "",
      "j": "",
      "n1": "8.6",
      "n2": "0.0",
      "mi": "4.3",
      "mfd": "2.1",
      "qual_sub": "",
      "pf": "",
      "data_a": "",
      "data_b": "",
      "data_c": "",
      "data_d": "",
      "data_e": "",
      "data_f": "",
      "data_g": "",
      "data_h": "",
      "data_i": "",
      "data_j": "",
      "falta": "03.30",
      "formula": "NI1  = (A*2 + B*1 + C*7)/10 NI2  = (F*1 + G*9)/10 MI = (NI1*5 + NI2*5) / 10 + PARTIC MF = (MI + PF) / 2",
      "Escola": ""
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "Codigo": "ENEX01484",
      "Disciplina": "CONVERSAO DE ENERGIA",
      "a": "8.5",
      "b": "",
      "c": "",
      "d": "",
      "e": "",
      "f": "",
      "g": "",
      "h": "",
      "i": "",
      "j": "",
      "n1": "8.5",
      "n2": "0.0",
      "mi": "4.2",
      "mfd": "2.1",
      "qual_sub": "",
      "pf": "",
      "data_a": "",
      "data_b": "",
      "data_c": "",
      "data_d": "",
      "data_e": "",
      "data_f": "",
      "data_g": "",
      "data_h": "",
      "data_i": "",
      "data_j": "",
      "falta": "00.00",
      "formula": "NI1  = (A*5)/5 NI2  = (F*5)/5 MI = (NI1*5 + NI2*5) / 10 + PARTIC MF = (MI + PF) / 2",
      "Escola": ""
    },
    {
      "nome_aluno": "EVANDRO REMON PULZ VIVA",
      "Codigo": "ENEX00926",
      "Disciplina": "ELETRONICA APLICADA I",
      "a": "10.0",
      "b": "10.0",
      "c": "",
      "d": "",
      "e": "",
      "f": "",
      "g": "",
      "h": "",
      "i": "",
      "j": "",
      "n1": "10.0",
      "n2": "0.0",
      "mi": "5.0",
      "mfd": "2.5",
      "qual_sub": "",
      "pf": "",
      "data_a": "",
      "data_b": "",
      "data_c": "",
      "data_d": "",
      "data_e": "",
      "data_f": "",
      "data_g": "",
      "data_h": "",
      "data_i": "",
      "data_j": "",
      "falta": "00.00",
      "formula": "NI1  = (A*7 + B*3)/10 NI2  = (F*9 + G*1)/10 MI = (NI1*5 + NI2*5) / 10 MF = (MI + PF) / 2",
      "Escola": ""
    }
  ]
}
