//
//  SchedulesModels.swift
//  MackTIA
//
//  Created by Luciano Moreira Turrini on 8/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct SchedulesRequest { }

struct SchedulesResponse {
    var schedules:[Schedule]
    var error:ErrorCode?
}

struct SchedulesViewModel {
    struct Success {
        var displayedSchedules: [Int : [Schedule]]
    }
    
    struct Error {
        var errorMessage:String
        var errorTitle:String
    }
}
