//
//  SchedulesInteractor.swift
//  MackTIA
//
//  Created by Luciano Moreira Turrini on 8/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SchedulesInteractorInput {
    func fetchSchedules(_ request: SchedulesRequest)
}

protocol SchedulesInteractorOutput {
    func presentFetchedSchedules(_ response: SchedulesResponse)
}

class SchedulesInteractor: SchedulesInteractorInput {
    var output: SchedulesInteractorOutput!
    var worker: SchedulesWorker!
  
    // MARK: Business logic
    func fetchSchedules(_ request: SchedulesRequest) -> Void {
        worker = SchedulesWorker()
        worker.fetchSchedules { [weak copySelf = self] (schedules, error) in
            let response = SchedulesResponse(schedules: schedules, error: error)
            copySelf?.output.presentFetchedSchedules(response)
        }
    }
}
