//
//  AbsenceModels.swift
//  MackTIA
//
//  Created by Aleph Retamal on 4/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct AbsenceRequest { }

struct AbsenceResponse {
    var absences:[Absence]
    var error:ErrorCode?
}

struct AbsenceViewModel {
    struct Success {
        var displayedAbsences:[Absence]
    }
    
    struct Error {
        var errorMessage:String
        var errorTitle:String
    }
}
   