//
//  AbsenceConfigurator.swift
//  MackTIA
//
//  Created by Aleph Retamal on 4/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension AbsenceViewController: AbsencePresenterOutput
{
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
    {
        router.passDataToNextScene(segue)
    }
}

extension AbsenceInteractor: AbsenceViewControllerOutput
{
}

extension AbsencePresenter: AbsenceInteractorOutput
{
}

class AbsenceConfigurator
{
    // MARK: Object lifecycle
    
    class var sharedInstance: AbsenceConfigurator
    {
        struct Static {
            static var instance: AbsenceConfigurator?
            static var token: dispatch_once_t = 0
        }
        
        dispatch_once(&Static.token) {
            Static.instance = AbsenceConfigurator()
        }
        
        return Static.instance!
    }
    
    // MARK: Configuration
    
    func configure(viewController: AbsenceViewController)
    {
        let router = AbsenceRouter()
        router.viewController = viewController
        
        let presenter = AbsencePresenter()
        presenter.output = viewController
        
        let interactor = AbsenceInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
