//
//  LoginWorker.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class LoginWorker {
    // MARK: Business Logic
    
    func validadeLogin(request: LoginRequest, completionHandler: (response: Bool, error: ErrorCode?)->Void){
        
        TIAServer.sharedInstance.sendRequet(.Login) { (jsonData, error) in
            let success = error == nil ? true : false
            completionHandler(response: success, error: error)
        }

    }
}
