//
//  LoginWorker.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 14/04/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class LoginWorker {
    // MARK: Business Logic
    
    func validadeLogin(request: LoginRequest, completionHandler: (response: Bool, error: ErrorCode?)->Void){
        
        let user = User(name: nil, tia: request.tia, password: request.password, campus: request.campus)
        TIAServer.sharedInstance.user = user
        // TODO: depois que resolver a mudanca na API voltar para requisicao do tipo login
        TIAServer.sharedInstance.sendRequet(ServiceURL.Absence) { (jsonData, error) in
            
            guard error == nil else {
                completionHandler(response: false, error: error)
                return
            }
            
            guard jsonData != nil else {
                completionHandler(response: false, error: ErrorCode.OtherFailure(title: NSLocalizedString("login_defaultErrorTitle", comment: "Something is wrong with the Server"), message: NSLocalizedString("login_defaultErrorMessage", comment: "Related message")))
                return
            }
            
            if let _ = jsonData!["erro"] as? String  {
                let errorMessage = jsonData?["erro"]
                print(#function, "Server report error: \(errorMessage)")
                completionHandler(response: false, error: ErrorCode.InvalidLoginCredentials(title: NSLocalizedString("error_invalidLoginCredentials_title", comment: "User credentials error"), message: NSLocalizedString("error_invalidLoginCredentials_message", comment: "User credentials error")))
                return
            }
            
            // TODO: Nao esta convertendo corretamente
            
            if let response = jsonData!["resposta"] as? [AnyObject],
                let name = response[0]["nome_aluno"] as? String {
                    TIAServer.sharedInstance.user!.name = name
            }
            
            TIAServer.sharedInstance.registerLogin()
            completionHandler(response: true, error: nil)
        }
    }
}
