//
//  AbsencePresenter.swift
//  MackTIA
//
//  Created by Aleph Retamal on 4/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AbsencePresenterInput
{
    func presentFetchedAbsences(response: AbsenceResponse)
}

protocol AbsencePresenterOutput: class
{
    func displayFetchedAbsences(viewModel: AbsenceViewModel)
}

class AbsencePresenter: AbsencePresenterInput
{
    weak var output: AbsencePresenterOutput!
    
    // MARK: Presentation logic
    
    func presentFetchedAbsences(response: AbsenceResponse) {
        let viewModel = AbsenceViewModel(displayedAbsences: response.absences)
        output.displayFetchedAbsences(viewModel)
    }
}
