//
//  AbsenceWorker.swift
//  MackTIA
//
//  Created by Aleph Retamal on 4/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class AbsenceWorker {
    // MARK: Business Logic
    
    func fetchAbsences(completionHandler:(absences:[Absence]) -> Void) {
        TIAServer.sharedInstance.sendRequet(.Absence) { (jsonData, error) in
            guard let _  = jsonData,
                response = jsonData!["resposta"] as? [NSDictionary] else {
                    completionHandler(absences: [])
                    return
            }
            
            var absences:[Absence] = []
            
            for absenceData in response {
                
                // TODO: PEGAR O RESTO DOS ATRIBUTOS
                guard let
                    dadas      = absenceData["dadas"] as? Int,
                    disciplina = absenceData["disciplina"] as? String,
                    faltas     = absenceData["faltas"] as? Int else {
                        continue
                }
                
                // TODO: ADD OS ATRIBUTOS AQUI
                absences.append(Absence(
                    dadas: dadas,
                    disciplina: disciplina,
                    faltas: faltas)
                )
            }
            
            completionHandler(absences: absences)
        }
    }
}
