//
//  AbsenceInteractor.swift
//  MackTIA
//
//  Created by Aleph Retamal on 4/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AbsenceInteractorInput {
    func fetchAbsences(request: AbsenceRequest)
}

protocol AbsenceInteractorOutput {
    func presentFetchedAbsences(response: AbsenceResponse)
}

class AbsenceInteractor: AbsenceInteractorInput {
    var output: AbsenceInteractorOutput!
    var worker: AbsenceWorker!
    
    // MARK: Business logic
    
    func fetchAbsences(request: AbsenceRequest) {
        worker = AbsenceWorker()
        worker.fetchAbsences { (absences) in
            let response = AbsenceResponse(absences: absences)
            self.output.presentFetchedAbsences(response)
        }
    }
}
